version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - sam package --template-file template.yml --s3-bucket $S3_ARTIFACT_BUCKET --output-template-file packaged.yml

artifacts:
  secondary-artifacts:
    nemurenai:
      files:
        - "**/template.yml"
    oyasumi:
      files:
        - '**/packaged.yml'
    usimitu:
      files:
        - '**/*.yml'
