AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: HelloWorldFunction
      Handler: app.lambda_handler
      CodeUri: hello_world
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  
  # HelloWorldFunction2:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     FunctionName: HelloWorldFunction2
  #     Handler: app.lambda_handler
  #     CodeUri: ./hello_world2
  #     Runtime: python3.8

  HelloWorldFunction3:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: HelloWorldFunction3
      Handler: app.lambda_handler
      CodeUri: hello_world3
      Runtime: python3.8
      Events:
        HelloWorldSNS:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:064319554215:sample-for-normal-lambda-hand
